### ISSUE TITLE
Great Initiative, thank you! Can this be copied/distributed?

### ISSUE THREAD

**Issue by timmwille** [Flowwie/flowwie-freecad#3]
I would like to fork the Repo, but not sure if Pull Requests for new Ideas or even adaptations are welcomed? could not find an Open Source License and not sure if this is copyright protected or free to use, with respective attribution of course.

Thanks for the initiative, love your tutorials.

Kannst auch auf Deutsch antworten.

**Comment by Flowwie** [comment]
Hi Tim!
I'm not a lawyer and don't know anything about that licensing stuff and I don't want to bother myself with it.
The stuff is completely free to use for anybody - but it would be very nice to attribute me and my YouTube channel "flowwies corner". Thank you for the request and have a good time!

**Comment by timmwille** [comment]
thx for the info 

Tip1: just Create new Markdown file [LICENSE.md](https://github.com/Flowwie/flowwie-freecad/new/main) to the repo and while creating, on the top right a template button pops up, no need to be a lawyer, GitHub guides you through →for example go for the simple MIT License, it has all you described)
Example (not Markdown in this case): https://github.com/timmwille/WhateveryouwantToNameIt/blob/main/LICENSE

Tip2: If you edit your Username in the LICENSE.md and link it to your YouTube like this, every fork contains a clear copy of that redirect to your channel `Copyright (c) 2020 [Flowwie](https://www.youtube.com/user/stolz3d)`

![grafik](https://user-images.githubusercontent.com/8081055/103670000-545dc280-4f79-11eb-9015-d55a25537d44.png)


Hope this might be of help, keep up the great work, will share it around :+1:

**Comment by hkienle** [comment]
@timmwille yes, I think that's all that would be required. I am not paranoid, but it is always nice to have a clear license statement to work with so there are no surprises on both ends!

**Comment by Thorbijoern** [comment]
@Flowwie you should really consider adding a licence because currently nobody is allowed to copy/share/use/addapt/extend your work in a legal way... only you have the copyright...
also through licences you can make sure people have to give you the attribution to you and your channel.
you don't have to be a lawyer to make decisions about the licencing, the lawyer work is allready done by institutions like the MIT, Creative Commons or the Free Software Foundation (to name a few big ones).
also most open licences are intentionally kept pretty simple so everyone can understand them.
github made a whole website to explain licencing and help you choose a licence you like: https://choosealicense.com/

**Comment by timmwille** [comment]
@Thorbijoern easy, he did :wink:
https://youtu.be/K6NHg8RH_rU?t=25

thx @Flowwie amazing real time adoption

Little hint: the non commercial part is a bit tricky as it [prevents](https://mifactori.de/non-commercial-is-not-open-source/) non profit organisations and schools as well to collaborate with the content, therefore per Definition the ['CC-BY'](https://creativecommons.org/licenses/by/4.0/legalcode) would be the Libre Open Source alternative as used in Open Educational Resources :relaxed:
But for private use and contributions it's now very clear, thank you!

Sorry for bothering you with this, as a mechanical engineering Enthusiast for Open Source Hardware I kind of ended up being a bit nerdy about it :smile:
I'm learning something new from your videos every time, hope you get this as a positive thing I added here to help, not stopping you too much from the work you do (believe me I've been there, diving in all this legal stuff for good) 
Cheers
